#!/bin/bash
############################################################################
#
#   Script to remove installed docker images from an existing IVA installation
#
#   Generated by va-ansible installer on: {{ ansible_date_time.iso8601 }}
#   Author: Robin Mulkers
#
############################################################################

{% for item in new_images %}
echo "Removing image {{ item.name }}:{{ item.tag }}"
docker rmi {{ item.id }}
{% endfor %}
