---
############################################################################
#
#   Ansible tasks from ivatools.system role configuring RHEL repositories
#       used for installing IBM Video Analytics
#
#   Tested on 26 Oct 2020
#   Author: Robin Mulkers
#
############################################################################
- name: "[repos-RedHat.yml] starting"
  set_fact: pf="[repos-RedHat.yml] "


- block:
  - name: "{{ pf }}Get enabled rhel repositories"
    shell:
      cmd: yum repolist|grep "rhel"|cut -f1 -d " "
      warn: no
    register: enabled_repos
  - debug:
      var:  enabled_repos
      verbosity: 1
  - name: "{{ pf }}Enable optional, extras and rhscl Repositories"
    command:
      cmd: subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"
    when: enabled_repos.stdout is not search("optional-rpms") or enabled_repos.stdout is not search("extras-rpms")
  - name: "{{ pf }}Enable rhscl Repository"
    command:
      cmd: subscription-manager repos --enable "rhel-*-rhscl-rpms"
    when: ansible_architecture == "ppc64le" and enabled_repos.stdout is not search("rhscl-rpms")
  - name: "{{ pf }}Enable codeready-builder Repository"
    command:
      cmd: subscription-manager repos --enable "codeready-builder*-rpms"
      state: enabled
    when: ansible_distribution_major_version in [ 8 ] and enabled_repos.stdout is not search("codeready-builder")
  become: yes

- name: "{{ pf }}Epel repo check"
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo
  become: yes
#  when: ansible_architecture == 'x86_64'
- block:
  - name: "{{ pf }}Add epel-release package/ppc64le"
    package:
      name: epel-release
      state: "present"
    when: ansible_architecture == 'ppc64le'
  - name: "{{ pf }}Add EPEL repository/x86_64"
    yum_repository:
      name: epel
      description: EPEL Repository
      baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/$basearch/"
      gpgkey: "https://epel.mirror.constant.com//RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    when: ansible_architecture == 'x86_64'
  when: not epel_repo.stat.exists
  become: yes
