---
############################################################################
#
#   Ansible tasks for ivatools.docker role 
#       used for installing IBM Video Analytics
#
#   Tested on 14 Dec 2020
#   Author: Robin Mulkers
#
############################################################################
- name: "[{{ docker_package }}-{{ ansible_os_family }}-{{ ansible_architecture }}.yml] starting"
  set_fact: pf="[{{ docker_package }}-{{ ansible_os_family }}-{{ ansible_architecture }}.yml] "

#- name: "{{ pf }}Template a repo file to {{ docker_RedHat_repo }}"
#  template:
#    src: templates/docker-ce.repo.ppc64le
#    dest: '{{ docker_RedHat_repo }}'
#    owner: root
#    group: root
#    mode: '0644'

# https://developer.ibm.com/components/ibm-power/tutorials/install-docker-on-linux-on-power/

- name: "{{ pf }}Install container.d on Ubuntu"
  package:
    name: containerd
    state: present
  become: yes

- name: "{{ pf }}Installing docker-ce packages"
  apt:
    deb: "{{ docker-ppc64le-binaries[ ansible_distribution ].web_url }}{{ item }}"
  loop: "{{ docker-ppc64le-binaries[ ansible_distribution ].bin-packages }}"
  become: yes
