---
############################################################################
#
#   Ansible tasks for ivatools.docker role 
#       used for stopping docker
#
#   Tested on 26 Oct 2020
#   Author: Robin Mulkers
#
############################################################################

- name: "Starting docker service"
  service:
    state: restarted
    name: docker
    enabled: yes
  become: yes

- block:
  - name: "Testing docker"
    command: docker run --rm hello-world
    register: docker_check
    changed_when: false
    become: yes
  - debug:
      var: docker_check
      verbosity: 1
  - name: "Checking docker hello-world"
    debug:
      msg: "ERROR: Docker hello-world failed, {{ docker_package }} is not properly installed"
    changed_when: true
    when: docker_check.rc != 0 or docker_check.stdout is not search("Hello from Docker!")
