---
############################################################################
#
#   Ansible variables for ivatools.docker role 
#       used for installing IBM Video Analytics
#
#   Tested on 26 Oct 2020
#   Author: Robin Mulkers
#
############################################################################
docker_package: "docker-ce"
docker_RedHat_repo: '/etc/yum.repos.d/{{ docker_package }}.repo'
docker_apt_gpg_key: 'https://download.docker.com/linux/ubuntu/gpg'
docker_apt_finger_print: '0EBFCD88'
docker_apt_repository: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
docker_compose_bin: '/usr/local/bin/docker-compose'