---
############################################################################
#
#   Cleanup IVA installation files
#
#   Tested on 08 Dec 2020
#
############################################################################
- name: IBM Video Analytics Cleaning-up Installation files
  hosts: all
  gather_facts: no
  tasks:
  - name: "Setting ansible_become_password = ansible_password by default"
    set_fact:
      ansible_become_password: "{{ ansible_password }}"
    when: ansible_become_password is not defined
    tags: always
  
- name: IBM Video Analytics SSE Clean-up
  hosts:
  - sse
  - allinone
  tags:
  - sse
  gather_facts: no
  vars:
  tasks:
  - name: "Clean-up {{ temp_dir }}"
    file:
      path: "{{ temp_dir }}"
      state: absent
    become: yes
    tags: sse

- name: IBM Video Analytics DLE Uninstallation
  hosts:
  - dle
  - allinone
  tags:
  - dle
  gather_facts: no
  vars:
  tasks:
  - name: "Clean-up {{ temp_dir }}"
    file:
      path: "{{ temp_dir }}"
      state: absent
    become: yes

- name: IBM Video Analytics MILS Uninstallation
  hosts:
  - mils
  - allinone
  gather_facts: no
  vars:
  tasks:
  - name: "Clean-up {{ temp_dir }}"
    file:
      path: "{{ temp_dir }}"
      state: absent
    become: yes

