galaxy_info:
  author: IBM Watson Media
  description: docker tooling for IBM Video Analytics
  company: IBM Watson
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - video
    - videoanalytics
    - docker
    - server
    - ibm
dependencies: []