---
############################################################################
#
#   Ansible tasks for ivatools.nvidia role 
#       used for installing IBM Video Analytics
#
#   Tested on 26 Oct 2020
#   Author: Robin Mulkers
#
############################################################################
- name: "[nvidia-driver.yml] starting"
  set_fact: pf="[nvidia-driver.yml] "


- name: "{{ pf }}nvidia-smi check"
  command: nvidia-smi
  changed_when: false
  failed_when: false
  register: nvidia_smi

- debug:
    var: nvidia_smi.stdout_lines
#- name: "{{ pf }}Installing NVIDIA driver for {{ ansible_distribution }} {{ ansible_distribution_version }}/{{ ansible_architecture }}"

- include_tasks: "nvidia-driver-{{ ansible_os_family }}.yml"
  when: nvidia_smi.rc != 0
